  import type { Metadata } from "next";
  // import { Geist, Geist_Mono } from "next/font/google";
  import "./globals.css";
  import Header from "@/components/Header";
  import Sec1 from "../components/Sec1";

  export const metadata: Metadata = {
    title: "Netflix Pakistan - Films and Dramas",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body
          className={`antialiased`}
        >
          <Header />
          {children}
        </body>
      </html>
    );
  }
